// Demo answers with NO API key. Two modes:
//   - Paper in scope: answer is retrieved from the paper's own text, so any
//     fact actually written in the paper (e.g. "40 question variants") gets
//     answered, for every paper — not just the one with hand-written rules.
//   - No paper: a small set of scripted portal answers.
// When ANTHROPIC_API_KEY is set, /api/chat skips this file entirely.

import type { Paper } from "./content";

// Exact demo line for anything we can't ground in real content.
const OUT_OF_SCOPE = "I have no verified Esomar work on that yet.";

// ——— tiny keyword retrieval over the paper text ———

const STOP = new Set(
  ("the a an and or of to in on for with is are was were be been being this that " +
    "these those it its as at by from we our you your i they them their he she his " +
    "her which who what when where why how do does did can could should would will " +
    "more than not no about into over across per any some all most each also has have " +
    "had but so if then there here me my")
    .split(" ")
);

function tokenize(s: string): string[] {
  return s
    .toLowerCase()
    .replace(/[^a-z0-9\s]/g, " ")
    .split(/\s+/)
    .filter((w) => w.length >= 3 && !STOP.has(w));
}

// Prefix match so plurals/inflections still hit: variants↔variant,
// limitations↔limit, wording↔word.
function tokenMatch(a: string, b: string): boolean {
  if (a === b) return true;
  const min = Math.min(a.length, b.length);
  return min >= 4 && (a.startsWith(b) || b.startsWith(a));
}

function splitSentences(text: string): string[] {
  return text
    .split(/(?<=[.?!])\s+(?=[A-Z0-9"'])/)
    .map((s) => s.trim())
    .filter((s) => s.length > 20);
}

function paperSentences(paper: Paper): string[] {
  return [
    ...splitSentences(paper.abstract),
    ...paper.sections.flatMap((sec) => sec.paragraphs.flatMap(splitSentences)),
  ];
}

// Returns the best-matching sentence and its score for a question.
function bestSentence(question: string, paper: Paper): { text: string; score: number } {
  const qTokens = tokenize(question);
  const wantsNumber = /\bhow many\b|\bhow much\b|\bnumber\b|\bcount\b|percent|%|\bhow long\b/.test(
    question.toLowerCase()
  );
  let best = { text: "", score: 0 };
  for (const sentence of paperSentences(paper)) {
    const sTokens = tokenize(sentence);
    let score = 0;
    for (const qt of qTokens) {
      if (sTokens.some((st) => tokenMatch(qt, st))) score += 1;
    }
    // Reward a number when the question asks for a quantity
    if (wantsNumber && /\d/.test(sentence)) score += 1.5;
    if (score > best.score) best = { text: sentence, score };
  }
  return best;
}

// ——— hand-written prose for the flagship paper (nicer than raw sentences
// for broad "what were the findings / limitations" style questions) ———

type Rule = { keywords: string[]; answer: string };

const syntheticRules: Rule[] = [
  {
    keywords: ["method", "study", "design", "approach", "sample", "how many", "studies"],
    answer:
      "The authors ran three parallel studies: category attitudes in packaged foods (1,200 respondents per condition), concept evaluation for a new financial product (800 per condition), and brand perception in telecom (1,000 per condition). Each questionnaire was fielded identically to a managed human panel and to synthetic panels generated by three leading LLMs, using demographically conditioned personas matched to the human sample frame.",
  },
  {
    keywords: ["finding", "result", "conclude", "conclusion", "outcome", "minority", "distribution", "variance"],
    answer:
      "Two findings pull in opposite directions. On averages, synthetic panels are remarkably close to human ones — a mean gap of just 4.1 percentage points across 74 questions. But at the distribution level they fail systematically: responses cluster toward the middle of scales, minority viewpoints are under-represented by roughly half, and on a genuinely novel concept synthetic purchase intent overshot human intent by 19 points.",
  },
  {
    keywords: ["limitation", "caveat", "bias", "risk", "weakness", "critic"],
    answer:
      "The paper names three limitations: the persona-conditioning techniques reflect early-2026 practice and may not generalise to newer systems; both markets studied are data-rich Western markets heavily represented in LLM training data, so divergence is plausibly larger elsewhere; and only quantitative survey formats were tested.",
  },
  {
    keywords: ["summar", "tldr", "gist", "overview"],
    answer:
      "In one paragraph: synthetic panels reproduce attitudinal averages almost perfectly (within ~4 points) but systematically miss distributional variance, minority viewpoints, and reactions to novel concepts. The conclusion: use them for piloting and directional reads, never for decisions that depend on the edges of a distribution — and validate per use case.",
  },
];

function curatedAnswer(question: string, paper: Paper): string | null {
  if (paper.slug !== "synthetic-respondents") return null;
  const qTokens = tokenize(question);
  for (const rule of syntheticRules) {
    const hit = rule.keywords.some((k) => {
      const kt = tokenize(k);
      // multi-word keyword: all its tokens must appear; single word: prefix match
      // kt.length guard: a keyword that tokenizes to nothing (e.g. the
      // 2-letter "ai") must not vacuously match every question.
      return kt.length > 0 && kt.every((t) => qTokens.some((qt) => tokenMatch(qt, t)));
    });
    if (hit) return rule.answer;
  }
  return null;
}

// ——— public API ———

export function getMockAnswer(question: string, paper: Paper, selection?: string): string {
  const best = bestSentence(question, paper);

  // A strong sentence match means the fact is written in the paper — answer it.
  let answer: string;
  if (best.score >= 2) {
    answer = best.text;
  } else {
    const curated = curatedAnswer(question, paper);
    if (curated) {
      answer = curated;
    } else if (best.score >= 1) {
      // On-topic but no precise sentence — give the paper's abstract.
      answer = paper.abstract;
    } else {
      return OUT_OF_SCOPE; // genuinely nothing in the paper matches
    }
  }

  // Acknowledge a highlighted passage on the exchange it was attached to.
  return selection ? `Looking at the passage you highlighted — ${answer}` : answer;
}

// General assistant (no paper in scope): a few scripted portal answers.
const genericRules: Rule[] = [
  {
    keywords: ["ai", "market research", "happening", "trend", "new"],
    answer:
      "The conversation right now centres on synthetic respondents — LLM-simulated survey panels — and whether their answers can be trusted. Try searching \"AI in market research\" for the keynote debate from Congress 2026, the paper on validity and limits of simulated panels, and the companies building in this space.",
  },
  {
    keywords: ["recommend", "read", "paper", "start"],
    answer:
      "Start with \"Synthetic Respondents: Validity and Limits of LLM-Simulated Panels\" by Ortiz-Kramer and Adeyemi (2026). It's a 14-minute read and the most-discussed paper in the AI topic. Open it and highlight any passage — I can answer questions about it directly.",
  },
  {
    keywords: ["esomar", "who are", "member", "portal"],
    answer:
      "Esomar is the global community for insights, analytics and market research professionals — setting professional standards, publishing research, and connecting practitioners across 130+ countries since 1947. This portal is your member home: search any topic to get curated videos, research papers and companies, and ask me anything along the way.",
  },
];

const genericAnchors = [
  "esomar", "ai", "market", "research", "paper", "video", "company", "companies",
  "panel", "survey", "insight", "member", "directory", "congress", "synthetic",
  "llm", "respondent", "recommend", "read", "portal",
];

export function getGenericMockAnswer(question: string): string {
  const qTokens = tokenize(question);
  const onTopic = qTokens.some((qt) => genericAnchors.some((a) => tokenMatch(qt, a)));
  if (!onTopic) return OUT_OF_SCOPE;
  for (const rule of genericRules) {
    const hit = rule.keywords.some((k) => {
      const kt = tokenize(k);
      // kt.length guard: a keyword that tokenizes to nothing (e.g. the
      // 2-letter "ai") must not vacuously match every question.
      return kt.length > 0 && kt.every((t) => qTokens.some((qt) => tokenMatch(qt, t)));
    });
    if (hit) return rule.answer;
  }
  return OUT_OF_SCOPE;
}
