// Scripted answers for the demo. Picked by keyword so a live audience can ask
// natural questions about the paper and still get a sensible, on-topic reply.
// When ANTHROPIC_API_KEY is set, /api/chat skips this file entirely.

type Rule = {
  keywords: string[];
  answer: string;
};

const rules: Rule[] = [
  {
    keywords: ["method", "how did", "how was", "study design", "approach", "sample size", "how many"],
    answer:
      "The authors ran three parallel studies: category attitudes in packaged foods (1,200 respondents per condition), concept evaluation for a new financial product (800 per condition), and brand perception in telecom (1,000 per condition). Each questionnaire was fielded identically to a managed human panel and to synthetic panels generated by three leading LLMs, using demographically conditioned personas matched to the human sample frame. Comparison metrics were pre-registered: mean differences on closed questions, distributional overlap via Wasserstein distance, and blind thematic coding of open ends.",
  },
  {
    keywords: ["finding", "result", "conclude", "conclusion", "outcome", "show", "accurate", "valid", "minority", "viewpoint", "distribution", "variance", "middle", "cluster", "why"],
    answer:
      "Two findings pull in opposite directions. On averages, synthetic panels are remarkably close to human ones — a mean gap of just 4.1 percentage points on top-two-box scores across 74 questions. But at the distribution level they fail systematically: responses cluster toward the middle of scales, minority viewpoints are under-represented by roughly half, and on a genuinely novel concept, synthetic purchase intent overshot human intent by 19 points. The centre of opinion is reproduced well; its edges are not.",
  },
  {
    keywords: ["limit", "caveat", "bias", "risk", "problem", "weakness", "critic"],
    answer:
      "The paper names three limitations: the persona-conditioning techniques reflect early-2025 practice and may not generalise to newer systems; both markets studied are data-rich Western markets that are heavily represented in LLM training data, so divergence is plausibly larger elsewhere; and only quantitative survey formats were tested — qualitative and conversational uses raise separate validity questions. The authors also flag a subtler risk: synthetic data that is plausibly good creates misplaced confidence in exactly the use cases where it fails.",
  },
  {
    keywords: ["use", "practice", "when", "should i", "recommend", "apply", "safe", "framework", "decision"],
    answer:
      "The proposed framework is use-case based. Synthetic respondents are defensible for instrument piloting, question-wording tests, and directional reads on well-documented categories — situations where being somewhat wrong is cheap. They are not defensible for sizing minority segments, forecasting adoption of novel concepts, or any decision that depends on the shape of a distribution rather than its centre. The rule of thumb: validate per use case, never assume.",
  },
  {
    keywords: ["synthetic", "llm", "simulated", "persona", "what is", "mean", "explain", "definition"],
    answer:
      "A synthetic respondent is a large language model prompted to answer a survey as if it were a specific person — typically conditioned with a demographic persona ('a 34-year-old teacher in Lyon…'). Vendors generate whole simulated panels this way. The appeal is speed and cost; the open question, which this paper tests empirically, is whether those simulated answers behave like real human answers beyond surface plausibility.",
  },
  {
    keywords: ["summar", "tldr", "short", "gist", "about"],
    answer:
      "In one paragraph: the authors compared LLM-simulated survey panels with matched human samples across three studies. Synthetic panels reproduce attitudinal averages almost perfectly (within ~4 points) but systematically miss distributional variance, minority viewpoints, and reactions to novel concepts (overshooting intent by 19 points). Their conclusion: synthetic respondents belong in the toolkit for piloting and directional reads, but not for decisions that depend on the edges of a distribution — and every use case needs its own validation.",
  },
];

const fallback =
  "That touches on something the paper addresses indirectly. The core tension the authors keep returning to is that synthetic panels mirror the centre of human opinion very well — averages within about 4 points — while systematically missing variance, minority viewpoints and novelty. Whether that matters depends entirely on your use case, which is why they propose validating synthetic respondents per application rather than trusting them wholesale. Would you like the methodology or the practical framework in more detail?";

export function getMockAnswer(question: string, selection?: string): string {
  const q = question.toLowerCase();
  const rule = rules.find((r) => r.keywords.some((k) => q.includes(k)));
  const answer = rule ? rule.answer : fallback;

  // Acknowledge the highlighted passage on the first exchange so the
  // "talk to the selection" moment lands in the demo.
  if (selection) {
    return `Looking at the passage you highlighted — ${answer}`;
  }
  return answer;
}
